### ISSUE TITLE
Octree 代码框架命名问题

### ISSUE THREAD

**Issue by gbccccc** [NJUCG/Moer-lite#5]
相关文件：Octree.cpp 及 Octree.h

`primIdxBuffer` 是否应该命名为 `geomIdxBuffer` ？
以下代码段截取自 `void Octree::build()`
```
//* 构建八叉树
std::vector<int> primIdxBuffer(shapes.size());
std::iota(primIdxBuffer.begin(), primIdxBuffer.end(), 0);
root = recursiveBuild(boundingBox, primIdxBuffer);
```
以及函数声明
```
Octree::OctreeNode* Octree::recursiveBuild(const AABB& aabb,
	const std::vector<int>& primIdxBuffer)
```

**Comment by ChenxiZhou0619** [comment]
作业要求实现的加速结构在渲染时是一个两层结构。第一层作用在每个shape的级别，或者说加速是通过排除整个shape（比如cube、sphere或者mesh）完成的；而对于目前项目来说，加速结构真正起到较大作用一般是在第二层，即当场景中包括triangleMesh时，该triangleMesh内部的加速结构，该加速结构是通过对该shape内部的面元进行空间划分以达到减少求交加速的。
这个问题的出现是因为我们需要用一套接口实现一个逻辑上两层的加速结构。因此确实在命名上会造成一些疑惑。不过由于作业
在实现时主要是针对triangleMesh内部的每个triangle（也就是该shape的每个primitive），因此在这里解释一下。

**Comment by gbccccc** [comment]
理解了，非常感谢！
不过我还是希望日后能在手册或者注释中解释一下这部分令人疑惑的命名，或许能让未来做这部分实验的同学少走一点不必要的弯路。

**Comment by ChenxiZhou0619** [comment]
感谢你的建议！
